### ISSUE TITLE
Can't get it to run

### ISSUE THREAD

**Issue by zell-mbc** [kacpertopol/cam_board#1]
First of all, I think this is a brilliant idea, unfortunately I can't get it to run.
I am running Arch and installed the following dependencies:
```
yay -S python3
yay -S opencv
yay -S python-numpy
```
But when I run the script I get the below error:
```
$ ./cam_board        
Traceback (most recent call last):
  File "./cam_board", line 5, in <module>
    import cv2
ImportError: libhdf5.so.200: cannot open shared object file: No such file or directory
```
I had a quick look around online but couldn't find any reference to this file. Any other dependencies I might be missing?

**Comment by kacpertopol** [comment]
Hi. Line 5 imports opencv (cv2). Looks like it was not installed in python. You can verify this by running
`<user> $ python3`
and entering
`>>> import cv2`

I would suggest trying to install opencv (cv2) via 
`pip3`

**Comment by zell-mbc** [comment]
Right, the import cv2 gives an "not installed" error.
I then went ahead and installed pip but unfortunately stuck again:
```
thomas at hermes in ~
$ pip3 opencv
ERROR: unknown command "opencv"

thomas at hermes in ~
$ pip3 install opencv
Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not find a version that satisfies the requirement opencv (from versions: none)
ERROR: No matching distribution found for opencv

thomas at hermes in ~
$ sudo pip3 install opencv
ERROR: Could not find a version that satisfies the requirement opencv (from versions: none)
ERROR: No matching distribution found for opencv
```

**Comment by kacpertopol** [comment]
I think this might help:

https://stackoverflow.com/questions/51853018/how-do-i-install-opencv-using-pip

**Comment by geeseven** [comment]
Hey @zell-mbc,

See [this][0] forum thread about opencv-python and Arch packaging.

Edit, I was able to get the `cv2` module loaded by installing the `python-h5py` package.

```python
$ python
Python 3.8.6 (default, Sep 30 2020, 04:00:38) 
[GCC 10.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cv2
>>> 
```

And I was able to run the script.

```console
$ python cam_board
[ WARN:0] global /build/opencv/src/opencv-4.5.0/modules/videoio/src/cap_gstreamer.cpp (935) open OpenCV | GStreamer warning: Cannot query video position: status=0, value=-1, duration=-1
```

[0]: https://bbs.archlinux.org/viewtopic.php?id=259931

**Comment by kacpertopol** [comment]
I'm closing the issue. If it still does not work, please start a new one. Cheers

**Comment by zell-mbc** [comment]
Thanks @geeseven, the `python-h5py` package did do the trick. All up and running now and ready to test :+1:
