### ISSUE TITLE
Select camera

### ISSUE THREAD

**Issue by zell-mbc** [kacpertopol/cam_board#2]
It's working and I really like the idea and ease of use. However, the picture is a little blurred because I need to move quite far away from the camera to make things work in my setup. If I was able to select the camera I'd be able to use my second USB cam which I'd put on a stand with the cam facing downwards, almost like in the good old days of overhead projectors :-)

**Comment by kacpertopol** [comment]
Hi, I added the `-c` option to chose the camera number. By default, if the option is not set, the camera number is set to 0 (the first camera). You can try setting it to 1 or some different integer. Unfortunately I only have one built in camera so I can't test this. Please let me know if it worked. 

If it fails then the program should stop and an error message printed to stdout. Could you paste this message here if it fails?

**Comment by zell-mbc** [comment]
-c 0 connects to the built in camera
-c 1 gave me an error
-c 2 connects to the USB cam

So things work fine. Why my USB cam is on slot 2 instead on 1 I don't know, and I doesn't matter to me.
Thanks for turning this around so quickly. Now I need to 3d print a camera stand :-)

Here's the error in case you want to catch the exception in a future version:
```
[ WARN:0] global /build/opencv/src/opencv-4.5.0/modules/videoio/src/cap_gstreamer.cpp (480) isPipelinePlaying OpenCV | GStreamer warning: GStreamer: pipeline have not been created
[ WARN:0] global /build/opencv/src/opencv-4.5.0/modules/videoio/src/cap_v4l.cpp (893) open VIDEOIO(V4L2:/dev/video1): can't open camera by index
QSettings::value: Empty key passed
QSettings::value: Empty key passed
Traceback (most recent call last):
  File "cam_board", line 85, in <module>
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
cv2.error: OpenCV(4.5.0) /build/opencv/src/opencv-4.5.0/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in f
```
