### ISSUE TITLE
Center A4 page

### ISSUE THREAD

**Issue by InFerYes** [kacpertopol/cam_board#9]
Hi, I have some documents here that I would like to show to people in meetings. This tool has been very helpful, but it crops on all sides.

I'm using the A4 tiny template and have a high resolution camera.

Perhaps if I could print the ARUCO markers in the corners of a sheet of paper it would solve this issue, but I'm not sure if it would warp/stretch the content of the pages to 16:9 or if it would keep a correct ratio of A4 (1:√2) on the screen? My papers are in landscape, not portrait.

**Comment by kacpertopol** [comment]
Hi, sorry for the late reply. 

Most of the files in the `to_print` directory have the markers placed such that their outsides form a rectangle with a 16:9 width to height ratio. This means that if you have a 16:9 web cam then the aspect ration of whatever you're writing should be preserved. The files `a4_16_by_9_tiny_inside.pdf` and `a4_16_by_9_tiny_inside.svg` have a slightly different marker placement. In this case it is the inside of the markers that forms a 16:9 rectangle, this is useful if you are using the `-r` option or the 'r' keyboard shortcut. 

If your web cam has a different aspect ratio then you can use the four ARUCO markers in `to_print/symbols` to create your own custom marker placement. These markers were generated using [this](https://chev.me/arucogen/) web app.
